[
  [
    {
      name: "Faster FF Breaker 4 Amp 1 Pole",
      quantity: 0,
      order: 0,
      price: 415,
    },
    {
      name: "Faster FF Breaker 6 Amp 1 Pole",
      quantity: 0,
      order: 0,
      price: 415,
    },
    {
      name: "Faster FF Breaker 10 Amp 1 Pole",
      quantity: 0,
      order: 0,
      price: 415,
    },
    {
      name: "Faster FF Breaker 16 Amp 1 Pole",
      quantity: 0,
      order: 0,
      price: 415,
    },
    {
      name: "Faster FF Breaker 20 Amp 1 Pole",
      quantity: 0,
      order: 0,
      price: 415,
    },
    {
      name: "Faster FF Breaker 32 Amp 1 Pole",
      quantity: 0,
      order: 0,
      price: 415,
    },
    {
      name: "Faster FF Breaker 63 Amp 1 Pole",
      quantity: 0,
      order: 0,
      price: 415,
    },
    {
      name: "Faster FF Breaker 32 Amp 2 Pole",
      quantity: 0,
      order: 0,
      price: 830,
    },
    {
      name: "Faster FF Breaker 63 Amp 2 Pole",
      quantity: 0,
      order: 0,
      price: 830,
    },
    {
      name: "Faster FF Breaker 32 Amp 3 Pole",
      quantity: 0,
      order: 0,
      price: 1520,
    },
    {
      name: "Faster FF Breaker 63 Amp 3 Pole",
      quantity: 0,
      order: 0,
      price: 1520,
    },
    {
      name: "Faster FF Breaker 63 Amp 4 Pole",
      quantity: 0,
      order: 0,
      price: 1920,
    },
    { name: "Faster FF E-L 63 Amp 2 Pole", quantity: 0, order: 0, price: 1900 },
    {
      name: "Faster FF Protector V+A 63 Amp 2 pol",
      quantity: 0,
      order: 0,
      price: 0,
    },
  ],
  [
    { name: "Entess V+A Protector 63 Amp 2 pol", quantity: 0, order: 0 },
    { name: "Faster FF Volt+Amp (Red)", quantity: 0, order: 0 },
    { name: "Round Volt Meter (Red)", quantity: 0, order: 0 },
    { name: "Round Volt Meter (Green)", quantity: 0, order: 0 },
    { name: "Round Volt Meter (Yellow)", quantity: 0, order: 0 },
    { name: "Round Volt Meter (White)", quantity: 0, order: 0 },
    { name: "Faster FF Wirless AC Bell", quantity: 0, order: 0 },
    { name: "Faster FF Wirless DC Bell", quantity: 0, order: 0 },
    { name: "Panel Light SMD (Red)", quantity: 0, order: 0 },
    { name: "Panel Light SMD (Green)", quantity: 0, order: 0 },
    { name: "Panel Light SMD (Yellow)", quantity: 0, order: 0 },
    { name: "Panel Light SMD (Blue)", quantity: 0, order: 0 },
    { name: "GA&DA SPD DC 2 Pol", quantity: 0, order: 0 },
    { name: "GA&DA SPD AC 2 Pol", quantity: 0, order: 0 },
    { name: "GA&DA SPD AC 4 Pol", quantity: 0, order: 0 },
    { name: "ATS GA&DA", quantity: 3, order: 0 },
    { name: "Volt Meter 60*60", quantity: 0, order: 0 },
    {
      name: "Faster FF Change Over Breaker 63 Amp 2 pol",
      quantity: 0,
      order: 0,
    },
    { name: "MC4 1000 Volt", quantity: 0, order: 0 },
    { name: "MC4 1500 Volt", quantity: 0, order: 0 },
    { name: "Faster FF 40 Amp Change Over", quantity: 0, order: 0 },
    { name: "Faster FF 50 Amp Change Over", quantity: 0, order: 0 },
    { name: "Schneider 63 Amp 2 Pole DC", quantity: 0, order: 0 },
    { name: "Schneider 125 Amp 2 Pole DC", quantity: 0, order: 0 },
  ],
  [
    { name: "Dell Breaker 4 Amp 1 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 6 Amp 1 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 10 Amp 1 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 16 Amp 1 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 20 Amp 1 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 32 Amp 1 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 63 Amp 1 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 32 Amp 2 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 63 Amp 2 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 32 Amp 3 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 63 Amp 3 Pole", quantity: 0, order: 0, price: 0 },
    { name: "Dell Breaker 63 Amp 4 Pole", quantity: 0, order: 0, price: 0 },
  ],
];
